version: "3"

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "3000:3000"

  mongo:
    image: mongo
